Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicStore.DatabaseContexts;
using MusicStore.Models;
using MusicStore.ViewModels;

namespace MusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private DatabaseContext _context;

        public ShoppingCartController(DatabaseContext context)
        {
            _context = context;

        }

        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext, _context);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedAlbum = _context.Albums
                .Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext, _context);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext, _context);

            // Get the name of the album to display confirmation
            string albumName = _context.Carts.Include(x => x.Album)
                .Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = WebUtility.HtmlEncode(albumName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }

    }
}

Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicStore.DatabaseContexts;
using MusicStore.Models;

namespace MusicStore.Controllers
{
    public class StoreController : Controller
    {
        private readonly DatabaseContext _context;

        public StoreController(DatabaseContext context)
        {
            _context = context;

        }

        public IActionResult Details(int id)
        {
            var album = _context.Albums.Include(z => z.Genre).Include(c => c.Artist).First(x => x.AlbumId == id);

            return View(album);
        }

        public IActionResult Index()
        {
            var genreModel = new List<Genre>
            {
                new Genre {Name = "Disco"},
                new Genre {Name = "Jazz"},
                new Genre {Name = "Rock"}
            };


            return View(genreModel);
        }

        public IActionResult Browse(string genre)
        {
            // Retrieve Genre and its Associated Albums from database
            var genreModel = _context.Genres.Include(x => x.Albums)
                .Single(g => g.Name == genre);

            return View(genreModel);
        }

 
    }

}

Views/Store/Browse.cshtml
@model Genre
@{
    ViewBag.Title = "Browse Albums";
}

<div class="container">
    <div class="genre">
        <h3><em>@Model.Name</em> Albums</h3>

        @for (int i = 0; i < @Model.Albums.Count; i += 8)
        {
            var albums = @Model.Albums.Skip(i).Take(8).ToList();

            <div class="row">

                <ul id="album-list">
                    @foreach (var album in albums)
                    {
                        <li class="col-md-auto">
                            <a href="@Url.Action("Details", new {id=album.AlbumId})">
                                <img alt="@album.Title" src="@album.AlbumArtUrl" />
                                <span>@album.Title</span>
                            </a>
                        </li>
                    }
                </ul>
            </div>
        }
    </div>
</div>

Views/Store/Details.cshtml
@model MusicStore.Models.Album

@{
    ViewBag.Title = "Album - " + Model.Title;
    Layout = "_Layout";
}

<h2>Album: @Model.Title</h2>
<h2>@Model.Title</h2>
<p>
    <img alt="@Model.Title"
         src="@Model.AlbumArtUrl" />
</p>
<div id="album-details">
    <p>
        <em>Genre:</em>
        @Model.Genre.Name
    </p>
    <p>
        <em>Artist:</em>
        @Model.Artist.Name
    </p>
    <p>
        <em>Price:</em>
        @($"{Model.Price:F}")
    </p>
    <p class="button">
        @Html.ActionLink("Add to cart", "AddToCart", 
            "ShoppingCart", new { id = Model.AlbumId }, "")
    </p>
</div>

Views/Store/Index.cshtml
@model IEnumerable<MusicStore.Models.Genre>

@{
    ViewData["Title"] = "Store";
}

<h1>Index</h1>

<h3>Browse Genres</h3>
<p>
    Select from @Model.Count()
    genres:</p>
<ul>
    @foreach (var genre in Model)
    {
        <li>@Html.ActionLink(genre.Name, "Browse", new { genre = genre.Name })</li>
    }
</ul>